### ISSUE TITLE
Index: Uneven scaling between fields

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/website#63]
First, loving the new website. Not often I commend design, but this is good stuff. :))))

Bottom of https://betaweb.weblate.org/en/
![Skjermbilde fra 2019-07-16 17 32 37](https://user-images.githubusercontent.com/13802408/61308076-c2e01b00-a7ef-11e9-8527-5c50bdb8bb4e.png)
160% scaling in FF 68

**Comment by nijel** [comment]
This is because of different length of text. Not sure if there is way in CSS to avoid this.

**Comment by milotype** [comment]
AFAIK, CSS flex-box actually can handle it. But in general, this is a matter of preference.

Nevertheless, I'd leave it as is. Why?
- English is not the only language. In some languages there might not even be a problem
- Depending on the streching of the browser's window and on language, the heights of the divs sometimes actually are equal
- Content of the two divs are not identical in length, so there is more "padding/whitespace" in the div with shorter text, when the divs have identical heights
- Hyphenation may play a role

So, IMO, it's better to keep a "natural flow" of text/content of divs contents!

BTW, in order to keep the "natural" linespacing between elements within the parent div, I suggest to remove the `min-height`in the style-css:1148 (correcting the class="box donate")
```
section.bottom .box {
    min-height: 400px;
...
}
```

Cheers,
Milo

**Comment by nijel** [comment]
Thanks, it makes sense and I will adjust it.
